"""Seed data for market scenarios."""

from backend.feature_store.store import MarketScenario, RuleCondition, upsert_market_scenario
import sqlite3

SCENARIOS = [
    {
        "name": "Reversal down",
        "parent_regime": "Trending down",
        "subtype": "sudden_reversal_down",
        "description": "Sharp reversal lower from prior rising or imbalance-up context.",
        "conditions": [
            {"indicator": "trend_yearly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "trend_quarterly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "trend_monthly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "trend_weekly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "band_position_yearly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "band_position_quarterly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "band_position_monthly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "band_position_weekly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "adr", "operator": "==", "value": "above MA", "weight": 3.0},
            {"indicator": "adr_slope", "operator": "==", "value": "sideways", "weight": 2.0},
            {"indicator": "rvol", "operator": ">", "value": 100.0, "weight": 5.0},
            {"indicator": "rvol_slope", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "vvix_vix_ratio", "operator": ">", "value": 6.0, "weight": 3.0},
            {"indicator": "delta_slope", "operator": "==", "value": "falling", "weight": 7.0},
            {"indicator": "gamma_regime", "operator": "==", "value": "mixed", "weight": 5.0},
            {"indicator": "vol_regime", "operator": "==", "value": "MODERATE", "weight": 4.0},
            {"indicator": "vwap_slope", "operator": "==", "value": "falling", "weight": 7.0},
            {"indicator": "cd_vs_ma", "operator": "==", "value": "below MA", "weight": 4.0},
        ]
    },
    {
        "name": "Breakdown from value",
        "parent_regime": "Trending down",
        "subtype": "breakdown_from_value",
        "description": "Breakdown lower from sideways or inside-value conditions.",
        "conditions": [
            {"indicator": "trend_yearly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "trend_quarterly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "trend_monthly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "trend_weekly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "band_position_yearly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "band_position_quarterly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "band_position_monthly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "band_position_weekly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "adr", "operator": "==", "value": "above MA", "weight": 3.0},
            {"indicator": "adr_slope", "operator": "==", "value": "sideways", "weight": 2.0},
            {"indicator": "rvol", "operator": ">", "value": 100.0, "weight": 5.0},
            {"indicator": "rvol_slope", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "vvix_vix_ratio", "operator": ">", "value": 6.0, "weight": 3.0},
            {"indicator": "delta_slope", "operator": "==", "value": "falling", "weight": 7.0},
            {"indicator": "gamma_regime", "operator": "==", "value": "negative", "weight": 5.0},
            {"indicator": "vol_regime", "operator": "==", "value": "HIGH", "weight": 4.0},
            {"indicator": "vwap_slope", "operator": "==", "value": "falling", "weight": 7.0},
            {"indicator": "cd_vs_ma", "operator": "==", "value": "below MA", "weight": 4.0},
        ]
    },
    {
        "name": "Continuation down",
        "parent_regime": "Trending down",
        "subtype": "continuation_down",
        "description": "Continuation of an existing downtrend or imbalance-down structure.",
        "conditions": [
            {"indicator": "trend_yearly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "trend_quarterly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "trend_monthly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "trend_weekly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "band_position_yearly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "band_position_quarterly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "band_position_monthly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "band_position_weekly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "adr", "operator": "==", "value": "above MA", "weight": 3.0},
            {"indicator": "adr_slope", "operator": "==", "value": "rising", "weight": 2.0},
            {"indicator": "rvol", "operator": ">", "value": 100.0, "weight": 5.0},
            {"indicator": "rvol_slope", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "vvix_vix_ratio", "operator": "<", "value": 5.0, "weight": 3.0},
            {"indicator": "delta_slope", "operator": "==", "value": "falling", "weight": 7.0},
            {"indicator": "gamma_regime", "operator": "==", "value": "negative", "weight": 5.0},
            {"indicator": "vol_regime", "operator": "==", "value": "EXTREME", "weight": 4.0},
            {"indicator": "vwap_slope", "operator": "==", "value": "falling", "weight": 7.0},
            {"indicator": "cd_vs_ma", "operator": "==", "value": "below MA", "weight": 4.0},
        ]
    },
    {
        "name": "Selloff after retest",
        "parent_regime": "Trending down",
        "subtype": "selloff_after_retest",
        "description": "Move lower after retest and rejection from upper value-area or VWAP-related levels.",
        "conditions": [
            {"indicator": "trend_yearly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "trend_quarterly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "trend_monthly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "trend_weekly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "band_position_yearly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "band_position_quarterly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "band_position_monthly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "band_position_weekly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "adr", "operator": "==", "value": "above MA", "weight": 3.0},
            {"indicator": "adr_slope", "operator": "==", "value": "falling", "weight": 2.0},
            {"indicator": "rvol", "operator": ">", "value": 100.0, "weight": 5.0},
            {"indicator": "rvol_slope", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "vvix_vix_ratio", "operator": ">", "value": 6.0, "weight": 3.0},
            {"indicator": "delta_slope", "operator": "==", "value": "falling", "weight": 7.0},
            {"indicator": "gamma_regime", "operator": "==", "value": "negative", "weight": 5.0},
            {"indicator": "vol_regime", "operator": "==", "value": "HIGH", "weight": 4.0},
            {"indicator": "vwap_slope", "operator": "==", "value": "falling", "weight": 7.0},
            {"indicator": "cd_vs_ma", "operator": "==", "value": "below MA", "weight": 4.0},
        ]
    },
    {
        "name": "V-reversal up",
        "parent_regime": "Trending up",
        "subtype": "v_reversal_up",
        "description": "Sharp reversal higher from prior falling or imbalance-down context.",
        "conditions": [
            {"indicator": "trend_yearly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "trend_quarterly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "trend_monthly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "trend_weekly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "band_position_yearly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "band_position_quarterly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "band_position_monthly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "band_position_weekly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "adr", "operator": "==", "value": "above MA", "weight": 3.0},
            {"indicator": "adr_slope", "operator": "==", "value": "rising", "weight": 2.0},
            {"indicator": "rvol", "operator": ">", "value": 100.0, "weight": 5.0},
            {"indicator": "rvol_slope", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "vvix_vix_ratio", "operator": "<", "value": 5.0, "weight": 3.0},
            {"indicator": "delta_slope", "operator": "==", "value": "rising", "weight": 7.0},
            {"indicator": "gamma_regime", "operator": "==", "value": "negative", "weight": 5.0},
            {"indicator": "vol_regime", "operator": "==", "value": "EXTREME", "weight": 4.0},
            {"indicator": "vwap_slope", "operator": "==", "value": "rising", "weight": 7.0},
            {"indicator": "cd_vs_ma", "operator": "==", "value": "above MA", "weight": 4.0},
        ]
    },
    {
        "name": "Breakout from value",
        "parent_regime": "Trending up",
        "subtype": "breakout_from_value",
        "description": "Breakout higher from sideways or inside-value conditions.",
        "conditions": [
            {"indicator": "trend_yearly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "trend_quarterly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "trend_monthly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "trend_weekly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "band_position_yearly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "band_position_quarterly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "band_position_monthly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "band_position_weekly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "adr", "operator": "==", "value": "above MA", "weight": 3.0},
            {"indicator": "adr_slope", "operator": "==", "value": "sideways", "weight": 2.0},
            {"indicator": "rvol", "operator": ">", "value": 100.0, "weight": 5.0},
            {"indicator": "rvol_slope", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "vvix_vix_ratio", "operator": "between", "value": "5,6", "weight": 3.0},
            {"indicator": "delta_slope", "operator": "==", "value": "rising", "weight": 7.0},
            {"indicator": "gamma_regime", "operator": "==", "value": "mixed", "weight": 5.0},
            {"indicator": "vol_regime", "operator": "==", "value": "HIGH", "weight": 4.0},
            {"indicator": "vwap_slope", "operator": "==", "value": "rising", "weight": 7.0},
            {"indicator": "cd_vs_ma", "operator": "==", "value": "above MA", "weight": 4.0},
        ]
    },
    {
        "name": "Continuation up",
        "parent_regime": "Trending up",
        "subtype": "continuation_up",
        "description": "Continuation of an existing uptrend or imbalance-up structure.",
        "conditions": [
            {"indicator": "trend_yearly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "trend_quarterly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "trend_monthly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "trend_weekly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "band_position_yearly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "band_position_quarterly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "band_position_monthly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "band_position_weekly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "adr", "operator": "==", "value": "above MA", "weight": 3.0},
            {"indicator": "adr_slope", "operator": "==", "value": "falling", "weight": 2.0},
            {"indicator": "rvol", "operator": ">", "value": 100.0, "weight": 5.0},
            {"indicator": "rvol_slope", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "vvix_vix_ratio", "operator": "between", "value": "5,6", "weight": 3.0},
            {"indicator": "delta_slope", "operator": "==", "value": "rising", "weight": 7.0},
            {"indicator": "gamma_regime", "operator": "==", "value": "mixed", "weight": 5.0},
            {"indicator": "vol_regime", "operator": "==", "value": "HIGH", "weight": 4.0},
            {"indicator": "vwap_slope", "operator": "==", "value": "rising", "weight": 7.0},
            {"indicator": "cd_vs_ma", "operator": "==", "value": "above MA", "weight": 4.0},
        ]
    },
    {
        "name": "Reclaim after retest",
        "parent_regime": "Trending up",
        "subtype": "reclaim_after_retest",
        "description": "Move higher after retest and reclaim from lower value-area or VWAP-related levels.",
        "conditions": [
            {"indicator": "trend_yearly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "trend_quarterly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "trend_monthly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "trend_weekly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "band_position_yearly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "band_position_quarterly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "band_position_monthly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "band_position_weekly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "adr", "operator": "==", "value": "above MA", "weight": 3.0},
            {"indicator": "adr_slope", "operator": "==", "value": "sideways", "weight": 2.0},
            {"indicator": "rvol", "operator": ">", "value": 100.0, "weight": 5.0},
            {"indicator": "rvol_slope", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "vvix_vix_ratio", "operator": "between", "value": "5,6", "weight": 3.0},
            {"indicator": "delta_slope", "operator": "==", "value": "rising", "weight": 7.0},
            {"indicator": "gamma_regime", "operator": "==", "value": "mixed", "weight": 5.0},
            {"indicator": "vol_regime", "operator": "==", "value": "HIGH", "weight": 4.0},
            {"indicator": "vwap_slope", "operator": "==", "value": "rising", "weight": 7.0},
            {"indicator": "cd_vs_ma", "operator": "==", "value": "above MA", "weight": 4.0},
        ]
    },
    {
        "name": "Up-first, then retrace",
        "parent_regime": "Normal variation day",
        "subtype": "up_first_then_retrace",
        "description": "Initial extension higher followed by retracement back into range.",
        "conditions": [
            {"indicator": "trend_yearly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "trend_quarterly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "trend_monthly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "trend_weekly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "band_position_yearly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "band_position_quarterly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "band_position_monthly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "band_position_weekly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "adr", "operator": "==", "value": "below MA", "weight": 3.0},
            {"indicator": "adr_slope", "operator": "==", "value": "falling", "weight": 2.0},
            {"indicator": "rvol", "operator": "between", "value": "80,100", "weight": 5.0},
            {"indicator": "rvol_slope", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "vvix_vix_ratio", "operator": "<", "value": 5.0, "weight": 3.0},
            {"indicator": "delta_slope", "operator": "==", "value": "rising", "weight": 7.0},
            {"indicator": "gamma_regime", "operator": "==", "value": "mixed", "weight": 5.0},
            {"indicator": "vol_regime", "operator": "==", "value": "MODERATE", "weight": 4.0},
            {"indicator": "vwap_slope", "operator": "==", "value": "rising", "weight": 7.0},
            {"indicator": "cd_vs_ma", "operator": "==", "value": "above MA", "weight": 4.0},
        ]
    },
    {
        "name": "Down-first, then retrace",
        "parent_regime": "Normal variation day",
        "subtype": "down_first_then_retrace",
        "description": "Initial extension lower followed by retracement back into range.",
        "conditions": [
            {"indicator": "trend_yearly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "trend_quarterly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "trend_monthly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "trend_weekly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "band_position_yearly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "band_position_quarterly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "band_position_monthly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "band_position_weekly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "adr", "operator": "==", "value": "below MA", "weight": 3.0},
            {"indicator": "adr_slope", "operator": "==", "value": "rising", "weight": 2.0},
            {"indicator": "rvol", "operator": "between", "value": "80,100", "weight": 5.0},
            {"indicator": "rvol_slope", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "vvix_vix_ratio", "operator": ">", "value": 6.0, "weight": 3.0},
            {"indicator": "delta_slope", "operator": "==", "value": "falling", "weight": 7.0},
            {"indicator": "gamma_regime", "operator": "==", "value": "mixed", "weight": 5.0},
            {"indicator": "vol_regime", "operator": "==", "value": "MODERATE", "weight": 4.0},
            {"indicator": "vwap_slope", "operator": "==", "value": "falling", "weight": 7.0},
            {"indicator": "cd_vs_ma", "operator": "==", "value": "below MA", "weight": 4.0},
        ]
    },
    {
        "name": "Trend-continuation variation",
        "parent_regime": "Normal variation day",
        "subtype": "trend_continuation_variation",
        "description": "Initial extension in the direction of the prevailing trend, then retracement.",
        "conditions": [
            {"indicator": "trend_yearly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "trend_quarterly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "trend_monthly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "trend_weekly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "band_position_yearly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "band_position_quarterly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "band_position_monthly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "band_position_weekly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "adr", "operator": "==", "value": "below MA", "weight": 3.0},
            {"indicator": "adr_slope", "operator": "==", "value": "falling", "weight": 2.0},
            {"indicator": "rvol", "operator": "between", "value": "80,100", "weight": 5.0},
            {"indicator": "rvol_slope", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "vvix_vix_ratio", "operator": "between", "value": "5,6", "weight": 3.0},
            {"indicator": "delta_slope", "operator": "==", "value": "rising", "weight": 7.0},
            {"indicator": "gamma_regime", "operator": "==", "value": "positive", "weight": 5.0},
            {"indicator": "vol_regime", "operator": "==", "value": "HIGH", "weight": 4.0},
            {"indicator": "vwap_slope", "operator": "==", "value": "rising", "weight": 7.0},
            {"indicator": "cd_vs_ma", "operator": "==", "value": "above MA", "weight": 4.0},
        ]
    },
    {
        "name": "Countertrend variation",
        "parent_regime": "Normal variation day",
        "subtype": "countertrend_variation",
        "description": "Temporary extension against broader context before rotation back into range.",
        "conditions": [
            {"indicator": "trend_yearly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "trend_quarterly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "trend_monthly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "trend_weekly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "band_position_yearly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "band_position_quarterly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "band_position_monthly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "band_position_weekly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "adr", "operator": "==", "value": "below MA", "weight": 3.0},
            {"indicator": "adr_slope", "operator": "==", "value": "rising", "weight": 2.0},
            {"indicator": "rvol", "operator": "between", "value": "80,100", "weight": 5.0},
            {"indicator": "rvol_slope", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "vvix_vix_ratio", "operator": "<", "value": 5.0, "weight": 3.0},
            {"indicator": "delta_slope", "operator": "==", "value": "rising", "weight": 7.0},
            {"indicator": "gamma_regime", "operator": "==", "value": "positive", "weight": 5.0},
            {"indicator": "vol_regime", "operator": "==", "value": "MODERATE", "weight": 4.0},
            {"indicator": "vwap_slope", "operator": "==", "value": "rising", "weight": 7.0},
            {"indicator": "cd_vs_ma", "operator": "==", "value": "above MA", "weight": 4.0},
        ]
    },
    {
        "name": "Value-area variation",
        "parent_regime": "Normal variation day",
        "subtype": "value_area_variation",
        "description": "Movement through or around value area followed by retracement back inside range.",
        "conditions": [
            {"indicator": "trend_yearly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "trend_quarterly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "trend_monthly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "trend_weekly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "band_position_yearly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "band_position_quarterly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "band_position_monthly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "band_position_weekly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "adr", "operator": "==", "value": "below MA", "weight": 3.0},
            {"indicator": "adr_slope", "operator": "==", "value": "sideways", "weight": 2.0},
            {"indicator": "rvol", "operator": "between", "value": "80,100", "weight": 5.0},
            {"indicator": "rvol_slope", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "vvix_vix_ratio", "operator": "between", "value": "5,6", "weight": 3.0},
            {"indicator": "delta_slope", "operator": "==", "value": "falling", "weight": 7.0},
            {"indicator": "gamma_regime", "operator": "==", "value": "positive", "weight": 5.0},
            {"indicator": "vol_regime", "operator": "==", "value": "MODERATE", "weight": 4.0},
            {"indicator": "vwap_slope", "operator": "==", "value": "falling", "weight": 7.0},
            {"indicator": "cd_vs_ma", "operator": "==", "value": "below MA", "weight": 4.0},
        ]
    },
    {
        "name": "Value-area balance",
        "parent_regime": "Neutral",
        "subtype": "value_area_balance",
        "description": "Consolidation and balance inside value area.",
        "conditions": [
            {"indicator": "trend_yearly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "trend_quarterly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "trend_monthly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "trend_weekly", "operator": "==", "value": "sideways", "weight": 3.0},
            {"indicator": "band_position_yearly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "band_position_quarterly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "band_position_monthly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "band_position_weekly", "operator": "==", "value": "inside VA", "weight": 3.0},
            {"indicator": "adr", "operator": "==", "value": "below MA", "weight": 3.0},
            {"indicator": "adr_slope", "operator": "==", "value": "falling", "weight": 2.0},
            {"indicator": "rvol", "operator": "<", "value": 80.0, "weight": 5.0},
            {"indicator": "rvol_slope", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "vvix_vix_ratio", "operator": "between", "value": "5,6", "weight": 3.0},
            {"indicator": "delta_slope", "operator": "==", "value": "sideways", "weight": 7.0},
            {"indicator": "gamma_regime", "operator": "==", "value": "positive", "weight": 5.0},
            {"indicator": "vol_regime", "operator": "==", "value": "LOW", "weight": 4.0},
            {"indicator": "vwap_slope", "operator": "==", "value": "sideways", "weight": 7.0},
            {"indicator": "cd_vs_ma", "operator": "==", "value": "above MA", "weight": 4.0},
        ]
    },
    {
        "name": "Demand-exhaustion neutral",
        "parent_regime": "Neutral",
        "subtype": "demand_exhaustion_neutral",
        "description": "Neutral balance after upside pressure stalls in rising or imbalance-up context.",
        "conditions": [
            {"indicator": "trend_yearly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "trend_quarterly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "trend_monthly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "trend_weekly", "operator": "==", "value": "rising", "weight": 3.0},
            {"indicator": "band_position_yearly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "band_position_quarterly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "band_position_monthly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "band_position_weekly", "operator": "==", "value": "imbalance up", "weight": 3.0},
            {"indicator": "adr", "operator": "==", "value": "below MA", "weight": 3.0},
            {"indicator": "adr_slope", "operator": "==", "value": "falling", "weight": 2.0},
            {"indicator": "rvol", "operator": "<", "value": 80.0, "weight": 5.0},
            {"indicator": "rvol_slope", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "vvix_vix_ratio", "operator": "between", "value": "5,6", "weight": 3.0},
            {"indicator": "delta_slope", "operator": "==", "value": "sideways", "weight": 7.0},
            {"indicator": "gamma_regime", "operator": "==", "value": "positive", "weight": 5.0},
            {"indicator": "vol_regime", "operator": "==", "value": "LOW", "weight": 4.0},
            {"indicator": "vwap_slope", "operator": "==", "value": "sideways", "weight": 7.0},
            {"indicator": "cd_vs_ma", "operator": "==", "value": "above MA", "weight": 4.0},
        ]
    },
    {
        "name": "Supply-exhaustion neutral",
        "parent_regime": "Neutral",
        "subtype": "supply_exhaustion_neutral",
        "description": "Neutral balance after downside pressure stalls in falling or imbalance-down context.",
        "conditions": [
            {"indicator": "trend_yearly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "trend_quarterly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "trend_monthly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "trend_weekly", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "band_position_yearly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "band_position_quarterly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "band_position_monthly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "band_position_weekly", "operator": "==", "value": "imbalance down", "weight": 3.0},
            {"indicator": "adr", "operator": "==", "value": "below MA", "weight": 3.0},
            {"indicator": "adr_slope", "operator": "==", "value": "falling", "weight": 2.0},
            {"indicator": "rvol", "operator": "<", "value": 80.0, "weight": 5.0},
            {"indicator": "rvol_slope", "operator": "==", "value": "falling", "weight": 3.0},
            {"indicator": "vvix_vix_ratio", "operator": "between", "value": "5,6", "weight": 3.0},
            {"indicator": "delta_slope", "operator": "==", "value": "sideways", "weight": 7.0},
            {"indicator": "gamma_regime", "operator": "==", "value": "positive", "weight": 5.0},
            {"indicator": "vol_regime", "operator": "==", "value": "LOW", "weight": 4.0},
            {"indicator": "vwap_slope", "operator": "==", "value": "sideways", "weight": 7.0},
            {"indicator": "cd_vs_ma", "operator": "==", "value": "below MA", "weight": 4.0},
        ]
    },
]

def seed_market_scenarios(conn: sqlite3.Connection) -> None:
    """Seed the 16 market scenarios into the database if they do not exist."""
    conn.row_factory = sqlite3.Row
    for sc_data in SCENARIOS:
        existing = conn.execute(
            "SELECT id FROM market_scenarios WHERE subtype = ?", 
            (sc_data["subtype"],)
        ).fetchone()
        
        if not existing:
            conditions = [RuleCondition(**c) for c in sc_data["conditions"]]
            scenario = MarketScenario(
                name=sc_data["name"],
                parent_regime=sc_data["parent_regime"],
                subtype=sc_data["subtype"],
                characteristics=sc_data["description"],
                conditions=conditions,
                risk_adjustments={},
                is_active=True
            )
            upsert_market_scenario(conn, scenario)

CRITERIA = [
    # ML
    {"name": "ml_regime_direction_alignment", "setup_type": "ML", "weight": 10.0, "condition": {"indicator": "subtype", "operator": "in", "value": "v_reversal_up,breakout_from_value,continuation_up,reclaim_after_retest", "weight": 10.0}},
    {"name": "ml_gamma_supports_move", "setup_type": "ML", "weight": 8.0, "condition": {"indicator": "gamma_regime", "operator": "in", "value": "negative,mixed", "weight": 8.0}},
    {"name": "ml_rvol_expansion", "setup_type": "ML", "weight": 7.0, "condition": {"indicator": "rvol", "operator": ">", "value": 100.0, "weight": 7.0}},
    {"name": "ml_rvol_trend_support", "setup_type": "ML", "weight": 5.0, "condition": {"indicator": "rvol_slope", "operator": "in", "value": "rising,sideways", "weight": 5.0}},
    {"name": "ml_delta_confirms_direction", "setup_type": "ML", "weight": 8.0, "condition": {"indicator": "delta_slope", "operator": "==", "value": "rising", "weight": 8.0}},
    {"name": "ml_cd_position_confirms_direction", "setup_type": "ML", "weight": 6.0, "condition": {"indicator": "cd_vs_ma", "operator": "==", "value": "above MA", "weight": 6.0}},
    {"name": "ml_vwap_slope_confirms_direction", "setup_type": "ML", "weight": 8.0, "condition": {"indicator": "vwap_slope", "operator": "==", "value": "rising", "weight": 8.0}},
    {"name": "ml_higher_timeframe_trend_alignment", "setup_type": "ML", "weight": 7.0, "condition": {"indicator": "trend_weekly", "operator": "in", "value": "rising", "weight": 7.0}},
    {"name": "ml_higher_timeframe_band_support", "setup_type": "ML", "weight": 6.0, "condition": {"indicator": "band_position_weekly", "operator": "in", "value": "Imbalance up", "weight": 6.0}},
    {"name": "ml_adr_supports_extension", "setup_type": "ML", "weight": 4.0, "condition": {"indicator": "adr_slope", "operator": "in", "value": "rising,sideways", "weight": 4.0}},
    {"name": "ml_neutral_regime_penalty", "setup_type": "ML", "weight": 9.0, "condition": {"indicator": "vol_regime", "operator": "in", "value": "LOW,VERY_LOW", "weight": 9.0}},
    {"name": "ml_vol_regime_supports_trade", "setup_type": "ML", "weight": 6.0, "condition": {"indicator": "vol_regime", "operator": "in", "value": "HIGH,EXTREME", "weight": 6.0}},
    {"name": "ml_entry_location", "setup_type": "ML", "weight": 6.0, "condition": {"indicator": "entry_quality", "operator": "in", "value": "Optimal,Good", "weight": 6.0}},

    # MS
    {"name": "ms_regime_direction_alignment", "setup_type": "MS", "weight": 10.0, "condition": {"indicator": "subtype", "operator": "in", "value": "sudden_reversal_down,breakdown_from_value,continuation_down,selloff_after_retest", "weight": 10.0}},
    {"name": "ms_gamma_supports_move", "setup_type": "MS", "weight": 8.0, "condition": {"indicator": "gamma_regime", "operator": "in", "value": "negative,mixed", "weight": 8.0}},
    {"name": "ms_rvol_expansion", "setup_type": "MS", "weight": 7.0, "condition": {"indicator": "rvol", "operator": ">", "value": 100.0, "weight": 7.0}},
    {"name": "ms_rvol_trend_support", "setup_type": "MS", "weight": 5.0, "condition": {"indicator": "rvol_slope", "operator": "in", "value": "rising,sideways", "weight": 5.0}},
    {"name": "ms_delta_confirms_direction", "setup_type": "MS", "weight": 8.0, "condition": {"indicator": "delta_slope", "operator": "==", "value": "falling", "weight": 8.0}},
    {"name": "ms_cd_position_confirms_direction", "setup_type": "MS", "weight": 6.0, "condition": {"indicator": "cd_vs_ma", "operator": "==", "value": "below MA", "weight": 6.0}},
    {"name": "ms_vwap_slope_confirms_direction", "setup_type": "MS", "weight": 8.0, "condition": {"indicator": "vwap_slope", "operator": "==", "value": "falling", "weight": 8.0}},
    {"name": "ms_higher_timeframe_trend_alignment", "setup_type": "MS", "weight": 7.0, "condition": {"indicator": "trend_weekly", "operator": "in", "value": "falling", "weight": 7.0}},
    {"name": "ms_higher_timeframe_band_support", "setup_type": "MS", "weight": 6.0, "condition": {"indicator": "band_position_weekly", "operator": "in", "value": "Imbalance down", "weight": 6.0}},
    {"name": "ms_adr_supports_extension", "setup_type": "MS", "weight": 4.0, "condition": {"indicator": "adr_slope", "operator": "in", "value": "rising,sideways", "weight": 4.0}},
    {"name": "ms_neutral_regime_penalty", "setup_type": "MS", "weight": 9.0, "condition": {"indicator": "vol_regime", "operator": "in", "value": "LOW,VERY_LOW", "weight": 9.0}},
    {"name": "ms_vol_regime_supports_trade", "setup_type": "MS", "weight": 6.0, "condition": {"indicator": "vol_regime", "operator": "in", "value": "HIGH,EXTREME", "weight": 6.0}},
    {"name": "ms_entry_location", "setup_type": "MS", "weight": 6.0, "condition": {"indicator": "entry_quality", "operator": "in", "value": "Optimal,Good", "weight": 6.0}},

    # MRL
    {"name": "mrl_regime_direction_alignment", "setup_type": "MRL", "weight": 10.0, "condition": {"indicator": "subtype", "operator": "in", "value": "countertrend_variation,value_area_variation", "weight": 10.0}},
    {"name": "mrl_gamma_supports_move", "setup_type": "MRL", "weight": 8.0, "condition": {"indicator": "gamma_regime", "operator": "in", "value": "positive,mixed", "weight": 8.0}},
    {"name": "mrl_rvol_expansion", "setup_type": "MRL", "weight": 7.0, "condition": {"indicator": "rvol", "operator": "between", "value": "80,100", "weight": 7.0}},
    {"name": "mrl_rvol_trend_support", "setup_type": "MRL", "weight": 5.0, "condition": {"indicator": "rvol_slope", "operator": "in", "value": "sideways,rising", "weight": 5.0}},
    {"name": "mrl_delta_confirms_direction", "setup_type": "MRL", "weight": 8.0, "condition": {"indicator": "delta_slope", "operator": "in", "value": "falling,sideways,rising", "weight": 8.0}},
    {"name": "mrl_cd_position_confirms_direction", "setup_type": "MRL", "weight": 6.0, "condition": {"indicator": "cd_vs_ma", "operator": "in", "value": "above MA,below MA", "weight": 6.0}},
    {"name": "mrl_vwap_slope_confirms_direction", "setup_type": "MRL", "weight": 8.0, "condition": {"indicator": "vwap_slope", "operator": "in", "value": "sideways,rising", "weight": 8.0}},
    {"name": "mrl_higher_timeframe_trend_alignment", "setup_type": "MRL", "weight": 7.0, "condition": {"indicator": "trend_weekly", "operator": "in", "value": "sideways,falling", "weight": 7.0}},
    {"name": "mrl_higher_timeframe_band_support", "setup_type": "MRL", "weight": 6.0, "condition": {"indicator": "band_position_weekly", "operator": "in", "value": "Inside value area,Imbalance down", "weight": 6.0}},
    {"name": "mrl_adr_supports_extension", "setup_type": "MRL", "weight": 4.0, "condition": {"indicator": "adr_slope", "operator": "in", "value": "sideways,rising", "weight": 4.0}},
    {"name": "mrl_neutral_regime_penalty", "setup_type": "MRL", "weight": 9.0, "condition": {"indicator": "vol_regime", "operator": "in", "value": "LOW,VERY_LOW", "weight": 9.0}},
    {"name": "mrl_vol_regime_supports_trade", "setup_type": "MRL", "weight": 6.0, "condition": {"indicator": "vol_regime", "operator": "==", "value": "MODERATE", "weight": 6.0}},
    {"name": "mrl_entry_location", "setup_type": "MRL", "weight": 6.0, "condition": {"indicator": "entry_quality", "operator": "in", "value": "Optimal,Good", "weight": 6.0}},

    # MRS
    {"name": "mrs_regime_direction_alignment", "setup_type": "MRS", "weight": 10.0, "condition": {"indicator": "subtype", "operator": "in", "value": "countertrend_variation,value_area_variation", "weight": 10.0}},
    {"name": "mrs_gamma_supports_move", "setup_type": "MRS", "weight": 8.0, "condition": {"indicator": "gamma_regime", "operator": "in", "value": "positive,mixed", "weight": 8.0}},
    {"name": "mrs_rvol_expansion", "setup_type": "MRS", "weight": 7.0, "condition": {"indicator": "rvol", "operator": "between", "value": "80,100", "weight": 7.0}},
    {"name": "mrs_rvol_trend_support", "setup_type": "MRS", "weight": 5.0, "condition": {"indicator": "rvol_slope", "operator": "in", "value": "sideways,rising", "weight": 5.0}},
    {"name": "mrs_delta_confirms_direction", "setup_type": "MRS", "weight": 8.0, "condition": {"indicator": "delta_slope", "operator": "in", "value": "rising,sideways,falling", "weight": 8.0}},
    {"name": "mrs_cd_position_confirms_direction", "setup_type": "MRS", "weight": 6.0, "condition": {"indicator": "cd_vs_ma", "operator": "in", "value": "below MA,above MA", "weight": 6.0}},
    {"name": "mrs_vwap_slope_confirms_direction", "setup_type": "MRS", "weight": 8.0, "condition": {"indicator": "vwap_slope", "operator": "in", "value": "sideways,falling", "weight": 8.0}},
    {"name": "mrs_higher_timeframe_trend_alignment", "setup_type": "MRS", "weight": 7.0, "condition": {"indicator": "trend_weekly", "operator": "in", "value": "sideways,rising", "weight": 7.0}},
    {"name": "mrs_higher_timeframe_band_support", "setup_type": "MRS", "weight": 6.0, "condition": {"indicator": "band_position_weekly", "operator": "in", "value": "Inside value area,Imbalance up", "weight": 6.0}},
    {"name": "mrs_adr_supports_extension", "setup_type": "MRS", "weight": 4.0, "condition": {"indicator": "adr_slope", "operator": "in", "value": "sideways,rising", "weight": 4.0}},
    {"name": "mrs_neutral_regime_penalty", "setup_type": "MRS", "weight": 9.0, "condition": {"indicator": "vol_regime", "operator": "in", "value": "LOW,VERY_LOW", "weight": 9.0}},
    {"name": "mrs_vol_regime_supports_trade", "setup_type": "MRS", "weight": 6.0, "condition": {"indicator": "vol_regime", "operator": "==", "value": "MODERATE", "weight": 6.0}},
    {"name": "mrs_entry_location", "setup_type": "MRS", "weight": 6.0, "condition": {"indicator": "entry_quality", "operator": "in", "value": "Optimal,Good", "weight": 6.0}},
]

from backend.feature_store.store import ScoringCriterion, upsert_scoring_criterion

def seed_scoring_criteria(conn: sqlite3.Connection) -> None:
    """Seed the 48 scoring criteria into the database if they do not exist."""
    conn.row_factory = sqlite3.Row
    for cr_data in CRITERIA:
        existing = conn.execute(
            "SELECT id FROM scoring_criteria WHERE name = ?", 
            (cr_data["name"],)
        ).fetchone()
        
        if not existing:
            cond = RuleCondition(**cr_data["condition"])
            criterion = ScoringCriterion(
                name=cr_data["name"],
                condition=cond,
                weight=cr_data["weight"],
                setup_type=cr_data["setup_type"],
                is_active=True
            )
            upsert_scoring_criterion(conn, criterion)
